kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen_service.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen_service/urls.py
from django.urls import path

from kitchen_service.views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)

urlpatterns = [
    path("", index, name="index"),

    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),

    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),

    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-type/<int:pk>/update/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
]

app_name = "kitchen"

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip"
             title="Designed and Coded by Creative Tim" data-placement="bottom">
            Restaurant Kitchen Service
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">

              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" href="{% url 'kitchen:cook-list' %}">
                  <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                  Cookers
                </a>
              </li>

              <li class="nav-item dropdown dropdown-hover mx-2"> <!-- Cuisines -->
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center"
                   href="{% url 'kitchen:dish-type-list' %}">
                  <i class="material-icons opacity-6 me-2 text-md">view_day</i>
                  Cuisines
                </a>
              </li>

              <li class="nav-item dropdown dropdown-hover mx-2"> <!-- Dishes -->
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" href="{% url 'kitchen:dish-list' %}">
                  <i class="material-icons opacity-6 me-2 text-md">article</i>
                  Dishes
                </a>
              </li>

              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="https://github.com/Yevheniy-Lototskiy/restaurant-kitchen-service" target="_blank"
                   class="btn btn-sm  bg-gradient-warning  mb-0 me-1 mt-2 mt-md-0">GitHub Project</a>
              </li>

              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom">Logout</p>
                  </a>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
<section class="py-3">
  <div class="container">
    <div class="row justify-space-between py-1">
      <div class="col-1 mx-auto">
        <ul class="pagination pagination-primary m-1">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">
                <span aria-hidden="true"><i class="material-icons" aria-hidden="true">chevron_left</i></span>
              </a>
            </li>
          {% endif %}
          <li class="page-item active">
            <span class="page-link">{{ page_obj.number }}</span>
          </li>
          {% if page_obj.has_next %}
            <li class="page-item">
              <a href="?page= {{ page_obj.next_page_number }}" class="page-link">
                <span aria-hidden="true"><i class="material-icons" aria-hidden="true">chevron_right</i></span>
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</section>

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>