kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen_service.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen_service/urls.py
from django.urls import path

from kitchen_service.views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)

urlpatterns = [
    path("", index, name="index"),

    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),

    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),

    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-type/<int:pk>/update/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
]

app_name = "kitchen"

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block title %} Delete {{ cook.first_name }} {{ cook.last_name }} {% endblock %}

{% block content %}
  <h1 class="text-center">Delete cook?</h1>
  <form action="" method="post" class="text-center">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url 'kitchen:cook-detail' pk=cook.pk %}">
      Cancel
    </a>
  </form>
{% endblock %}

{% block footer %}{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block title %} {{ cook.first_name }} {{ cook.last_name }} {% endblock %}

{% block body_class %} blog-author {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/bg6.jpg');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">

    <section class="py-sm-7 py-5 position-relative">
      <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-2 mx-md-auto">
        <div class="col-lg-8 text-center mx-auto my-auto">
          <h1 class="mb-0">{{ cook.first_name }} {{ cook.last_name }}</h1>
          <p class="col-lg-12 text-center mx-auto my-auto">
            {{ cook.years_of_experience }} year{{ cook.years_of_experience|pluralize }} of experience
          </p>
          <div>
            <button class="btn dropdown-toggle bg-gradient-warning" type="button" id="dropdownMenuButton"
                    data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </button>
            <ul class="dropdown-menu px-2 py-3" aria-labelledby="dropdownMenuButton">
              <li>
                <a class="dropdown-item border-radius-md bg-gradient-faded-light"
                   href="{% url 'kitchen:cook-update' pk=cook.id %}">
                  Update
                </a>
              </li>
              <li>
                <a class="dropdown-item border-radius-md bg-gradient-faded-light"
                   href="{% url 'kitchen:cook-delete' pk=cook.id %}">
                  Delete
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section class="py-3">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h3 class="mb-5">Check my dishes</h3>
          </div>
        </div>
        <div class="col">
          {% for dish in cook.dishes.all %}
            <div class="card-body px-0">
              <h5>
                <a href="{% url 'kitchen:dish-detail' pk=dish.id %}"
                   class="text-dark font-weight-bold">{{ dish.name }}</a>
              </h5>
              <p>
                {{ dish.description }}
              </p>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
  </div>

{% endblock content %}

{% block javascripts %}{% endblock javascripts %}

templates/kitchen/cook_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block title %} Cooker {% endblock %}

{% block stylesheets %}
{% endblock %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/bg6.jpg');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <div class="card-body">
          <div class="row">
            <div class="col-md-10 col-lg-8 mx-auto">
              <h2 class="card-title text-center">{{ object|yesno:"Update,Create" }} Cook</h2>
              <div class="input-group input-group-dynamic mb-4">
                <form role="form" id="contact-form" action="" method="post" novalidate class="w-100">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block javascripts %}
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %} Cookers {% endblock %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/bg6.jpg');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <section class="pt-4 pb-6" id="count-stats">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-2">
          <h1 class="col-lg-8 text-center mx-auto my-auto">Cookers</h1>
          <a href="{% url 'kitchen:cook-create' %}" class="btn btn-primary link-to-page">
            Add new Cooker
          </a>
        </div>
        <div class="row justify-content-center text-center">

          <section class="py-0">
            <div class="container">
              <div class="row justify-space-between py-0">
                <div class="col-lg-11 mx-auto">
                  <div class="input-group input-group-dynamic mb-5">
                    <form action="" method="get">
                      {{ search_form|crispy }}
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {% if cook_list %}
            <table class="table">
              <tr>
                <th class="text-gradient text-info">Username</th>
                <th class="text-gradient text-info">First name</th>
                <th class="text-gradient text-info">Last name</th>
                <th class="text-gradient text-info">Years of experience</th>
              </tr>
              {% for cook in cook_list %}
                <tr>
                  <td>
                    <a href="{% url 'kitchen:cook-detail' pk=cook.id %}">
                      {{ cook.username }}
                    </a>
                    {% if user == cook %} (Me){% endif %}
                  </td>
                  <td>{{ cook.first_name }}</td>
                  <td>{{ cook.last_name }}</td>
                  <td>{{ cook.years_of_experience }}</td>
                </tr>
              {% endfor %}
            </table>
          {% else %}
            <p>There are no cookers in the service.</p>
          {% endif %}

          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}

        </div>
      </div>
    </section>
  </div>

{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block title %} Delete {{ dish.name }} {% endblock %}

{% block content %}
  <h1 class="text-center">Delete dish?</h1>
  <form action="" method="post" class="text-center">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url 'kitchen:dish-detail' pk=dish.pk %}">
      Cancel
    </a>
  </form>
{% endblock %}

{% block footer %}{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block title %} {{ dish.name }} {% endblock %}

{% block body_class %}{% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/bg1.jpg');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">

    <section class="py-sm-7 py-5 position-relative">
      <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-2 mx-md-auto">
        <div class="col-lg-8 text-center mx-auto my-auto">
          <h1 class="mb-0">{{ dish.name }}</h1>
          <p class="col-lg-12 text-center mx-auto my-auto">
            {{ dish.description }}
          </p>
        </div>

        <div class="text-center">
          <button class="btn dropdown-toggle bg-gradient-warning" type="button" id="dropdownMenuButton"
                  data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </button>
          <ul class="dropdown-menu px-2 py-3" aria-labelledby="dropdownMenuButton">
            <li>
              <a class="dropdown-item border-radius-md bg-gradient-faded-light"
                 href="{% url 'kitchen:dish-update' pk=dish.id %}">
                Update
              </a>
            </li>
            <li>
              <a class="dropdown-item border-radius-md bg-gradient-faded-light"
                 href="{% url 'kitchen:dish-delete' pk=dish.id %}">
                Delete
              </a>
            </li>
          </ul>
        </div>
      </div>
    </section>

    <section class="py-3">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h3 class="mb-5">Cookers who know the secrets of this dish</h3>
          </div>
        </div>
        <div class="col">
          {% for cook in dish.cooks.all %}
            <div class="card-body px-0">
              <h5>
                <a href="{% url 'kitchen:cook-detail' pk=cook.id %}" class="text-dark font-weight-bold">
                  {{ cook.first_name }} {{ cook.last_name }}
                </a>
              </h5>
              <p>
                {{ cook.username }}, {{ cook.years_of_experience }} year{{ cook.years_of_experience|pluralize }} of
                experience
              </p>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
  </div>

{% endblock content %}

{% block javascripts %}{% endblock javascripts %}

templates/kitchen/dish_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block title %} Dish {% endblock %}

{% block stylesheets %}
{% endblock %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/bg1.jpg');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <div class="card-body">
          <div class="row">
            <div class="col-md-10 col-lg-8 mx-auto">
              <h2 class="card-title text-center">{{ object|yesno:"Update,Create" }} Dish</h2>
              <div class="input-group input-group-dynamic mb-4">
                <form role="form" id="contact-form" action="" method="post" novalidate class="w-100">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block javascripts %}
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %} Dishes {% endblock %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/bg1.jpg');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <section class="pt-4 pb-6" id="count-stats">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-2">
          <h1 class="col-lg-8 text-center mx-auto my-auto">Dishes</h1>
          <a href="{% url 'kitchen:dish-create' %}" class="btn btn-primary link-to-page">
            Add new Dish
          </a>
        </div>
        <div class="row justify-content-center text-center">

          <section class="py-0">
            <div class="container">
              <div class="row justify-space-between py-0">
                <div class="col-lg-11 mx-auto">
                  <div class="input-group input-group-dynamic mb-5">
                    <form action="" method="get">
                      {{ search_form|crispy }}
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {% if dish_list %}
            <table class="table">
              <tr>
                <th class="text-gradient text-info">Name</th>
                <th class="text-gradient text-info">Cuisine</th>
                <th class="text-gradient text-info">Price</th>
              </tr>
              {% for dish in dish_list %}
                <tr>
                  <td>
                    <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">
                      {{ dish.name }}
                    </a>
                  </td>
                  <td>{{ dish.dish_type.name }}</td>
                  <td>{{ dish.price }}</td>
                </tr>
              {% endfor %}
            </table>
          {% else %}
            <p>There are no dishes in the service.</p>
          {% endif %}

          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}

        </div>
      </div>
    </section>
  </div>

{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block title %} Delete cuisine {% endblock %}

{% block content %}
  <h1 class="text-center">Delete dish?</h1>
  <form action="" method="post" class="text-center">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url 'kitchen:dish-type-list' %}">
      Cancel
    </a>
  </form>
{% endblock %}

{% block footer %}{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block title %} Cuisine {% endblock %}

{% block stylesheets %}
{% endblock %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/bg4.jpg');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <div class="card-body">
          <div class="row">
            <div class="col-md-10 col-lg-8 mx-auto">
              <h2 class="card-title text-center">{{ object|yesno:"Update,Create" }} Cuisine</h2>
              <div class="input-group input-group-dynamic mb-4">
                <form role="form" id="contact-form" action="" method="post" novalidate class="w-100">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block javascripts %}
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %} Cuisines {% endblock %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/bg4.jpg');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <section class="pt-4 pb-6" id="count-stats">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-2">
          <h1 class="col-lg-8 text-center mx-auto my-auto">Cuisines</h1>
          <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-primary link-to-page">
            Add new Cuisine
          </a>
        </div>
        <div class="row justify-content-center text-center">

          <section class="py-0">
            <div class="container">
              <div class="row justify-space-between py-0">
                <div class="col-lg-11 mx-auto">
                  <div class="input-group input-group-dynamic mb-5">
                    <form action="" method="get">
                      {{ search_form|crispy }}
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {% if dish_type_list %}
            <table class="table">
              <tr>
                <th class="text-gradient text-info">Cuisine</th>
                <th class="text-gradient text-info">Edit</th>
              </tr>
              {% for dish_type in dish_type_list %}
                <tr>
                  <td>
                    {{ dish_type.name }}
                  </td>
                  <td>
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-bs-toggle="dropdown" aria-expanded="false">
                      Edit
                    </button>
                    <ul class="dropdown-menu px-2 py-3" aria-labelledby="dropdownMenuButton">
                      <li>
                        <a class="dropdown-item border-radius-md"
                           href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">
                          Update
                        </a>
                      </li>
                      <li>
                        <a class="dropdown-item border-radius-md"
                           href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">
                          Delete
                        </a>
                      </li>
                    </ul>
                  </td>
                  <td>{{ cook.last_name }}</td>
                </tr>
              {% endfor %}
            </table>
          {% else %}
            <p>There are no cuisines in the service.</p>
          {% endif %}

          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}

        </div>
      </div>
    </section>
  </div>

{% endblock %}

templates/kitchen/index.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block body_class %}{% endblock %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header class="bg-gradient-dark">
    <div class="page-header min-vh-75" style="background-image: url('{{ ASSETS_ROOT }}/img/bg9.jpg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Restaurant Kitchen Service</h1>
            <p class="lead mb-4 text-white opacity-8">Welcome to the Kitchen Service</p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <section class="pt-4 pb-6" id="count-stats">
      <div class="container">
        <div class="row mb-7">
        </div>
        <div class="row justify-content-center text-center">
          <div class="col-md-3">
            <h1 class="text-gradient text-info"><span id="state1" countTo="{{ num_dishes }}">0</span>+</h1>
            <h5>Dishes</h5>
          </div>
          <div class="col-md-3">
            <h1 class="text-gradient text-info"><span id="state2" countTo="{{ num_dish_types }}">0</span>+</h1>
            <h5>Types of Dishes</h5>
          </div>
          <div class="col-md-3">
            <h1 class="text-gradient text-info"><span id="state3" countTo="{{ num_cooks }}">0</span></h1>
            <h5>Cookers</h5>
          </div>
        </div>
      </div>
    </section>
  </div>

{% endblock content %}

{% block javascripts %}

  <script>
      // get the element to animate
      var element = document.getElementById('count-stats');
      var elementHeight = element.clientHeight;

      // listen for scroll event and call animate function

      document.addEventListener('scroll', animate);

      // check if element is in view
      function inView() {
          // get window height
          var windowHeight = window.innerHeight;
          // get number of pixels that the document is scrolled
          var scrollY = window.scrollY || window.pageYOffset;
          // get current scroll position (distance from the top of the page to the bottom of the current viewport)
          var scrollPosition = scrollY + windowHeight;
          // get element position (distance from the top of the page to the bottom of the element)
          var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

          // is scroll position greater than element position? (is element in view?)
          if (scrollPosition > elementPosition) {
              return true;
          }

          return false;
      }

      var animateComplete = true;

      // animate element when it is in view
      function animate() {

          // is element in view?
          if (inView()) {
              if (animateComplete) {
                  if (document.getElementById('state1')) {
                      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
                      if (!countUp.error) {
                          countUp.start();
                      } else {
                          console.error(countUp.error);
                      }
                  }
                  if (document.getElementById('state2')) {
                      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
                      if (!countUp1.error) {
                          countUp1.start();
                      } else {
                          console.error(countUp1.error);
                      }
                  }
                  if (document.getElementById('state3')) {
                      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
                      if (!countUp2.error) {
                          countUp2.start();
                      } else {
                          console.error(countUp2.error);
                      }
                      ;
                  }
                  animateComplete = false;
              }
          }
      }

      if (document.getElementById('typed')) {
          var typed = new Typed("#typed", {
              stringsElement: '#typed-strings',
              typeSpeed: 90,
              backSpeed: 90,
              backDelay: 200,
              startDelay: 500,
              loop: true
          });
      }
  </script>

  <script>
      if (document.getElementsByClassName('page-header')) {
          window.onscroll = debounce(function () {
              var scrollPosition = window.pageYOffset;
              var bgParallax = document.querySelector('.page-header');
              var oVal = (window.scrollY / 3);
              bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
          }, 6);
      }
  </script>

{% endblock javascripts %}